### ISSUE TITLE
act test failed when check return data exist

### ISSUE THREAD

**Issue by leeaee** [actframework/actframework#1010]
Test
```yml
  - description: admin login
    request:
      post: /api/v1/login
      params:
        username: root
        password: 111111
    response:
      status: 200
      json:
        token:
        - exists: true
```
Expect
Check the response inlcude token and pass test
Actually
Test falied
```log
[FAIL] Admin login
- Cannot verify token value[eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJuZXgiLCJqdGkiOiJkNzIxZWI5ZC0yZGUyLTQ3YjUtYWZhZi1mNmQ0Yjg0ODAxMWEiLCJ1c2VybmFtZSI6IjViZWQ3M2JjOGVhZjM3MWY0YzhjN2NlNCJ9.3aS1OmQxkwZv4ibYV3GPx1UbLVjjU5Kr6622ZMWT9m8~] against test[{exists=true}]
act.test.util.ErrorMessage: Cannot verify token value[eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJuZXgiLCJqdGkiOiJkNzIxZWI5ZC0yZGUyLTQ3YjUtYWZhZi1mNmQ0Yjg0ODAxMWEiLCJ1c2VybmFtZSI6IjViZWQ3M2JjOGVhZjM3MWY0YzhjN2NlNCJ9.3aS1OmQxkwZv4ibYV3GPx1UbLVjjU5Kr6622ZMWT9m8~] against test[{exists=true}]
```
ACT version:
ActFramework v1.8.16-SNAPSHOT-3cbb
