### ISSUE TITLE
Test - json param shall be processed

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#1025]
Given test scenario parts:

```yaml
  - description: delete other name
    request:
      delete: /api/v1/clients/${newClientId}/other-names
      json:
        - ${otherNameId}
```

It shall process the json array `${otherNameId}` while building the request
