### ISSUE TITLE
Test yaml - variable not evaluated when putting in an array

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#1055]
Here is a snippet of a test yaml file of our real project:

```yml
  - description: Create new Client
    request:
      post: /api/v1/clients
      json:
        clientName: ${newClientName}
        email: ${newClientEmail}
        tradingNames:
          - ${tradingName1}
          - ${tradingName2}
```

When we are running the testing, the variable `${newClientName}` and `{newClientEmail}` is evaluated, but the `${tradingName1}`  and `${tradingName2}` is transferred to backend in literal.
