### ISSUE TITLE
Act-Test - JSON request array content get dropped

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#1076]
Yaml file:

```yml
  interactions:
    - description: add other name list to the client
      request:
        post: other-names
        json:
          nameList:
            - foo
            - bar
```

Expected: the backend server received `nameList` with content "foo" and "bar"

Found: the backend server received an empty `nameList`.
