### ISSUE TITLE
Test Scenario - allow specify ignore reason

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#1158]
At the moment when we mark a scenario to be ignored, the only way to give the reason is to add a comment, e.g.

```yml
Scenario(CLAIM):
  # no data in the database after switched to new UAT environment
  ignore: true
  depends:
  - LOGIN
  interactions:
  - description: lookup claims by search string
  ...
```

And when we print out the test report, there is no way to mark why a test scenario is ignored in the report.

The CR is to make it able to specify the ignore reason in test scenario spec and report it in the final report.
