### ISSUE TITLE
Test Scenario - allow specify response spec without type block

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#1159]
At the moment it needs to specify response spec under the type block, e.g.

```yaml
    response:
      json:
        claimStatusText: Finalised
        claimId: 2454
        clientId:
          - exists: true
        dateNotified:
          - exists: true
```

The CR makes it possible to skip the `json` so we can do it like:

```yaml
    response:
      _type: json
      claimStatusText: Finalised
      claimId: 2454
      clientId:
        - exists: true
      dateNotified:
        - exists: true
```

Where `_type` could possible be omitted in the spec and the framework can infer it using the `Content-Type` header of the response or by default, make it JSON
