### ISSUE TITLE
Act-Test - dependency order not maintained when setup is true

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#1195]
For the following two scenarios: 

```yml
Scenario(ATC-63-admin-login):
  partition: admin
  setup: true
  refId: ADMIN_LOGIN
  depends:
    - ADMIN_LOGOUT
```

```yml
Scenario(ATC-66-admin-logout):
  refId: ADMIN_LOGOUT
  partition: admin
```

Scenario `ADMIN_LOGIN` is a **setup** scenario for partition `admin`, meaning it needs to be run before each scenario in the partition. At the same time `ADMIN_LOGIN` depends on `ADMIN_LOGOUT`. So the execute order should be:

1. ADMIN_LOGOUT
2. ADMIN_LOGIN
3. other scenarios of admin partition

However what we found is sometimes it executes `ADMIN_LOGIN` before `ADMIN_LOGOUT`:
![image](https://user-images.githubusercontent.com/216930/62402603-ebc42680-b5cb-11e9-99e6-b7b121a6733c.png)

And this breaks the logic, as result all following scenario failed.
