### ISSUE TITLE
Act-Test - add an `entityId()` function

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#1240]
At the moment we have defined functions for generate id for entity, e.g.

```
Scenario(View bookmark - exceptional cases):
  issueKey: 6
  depends:
    - Update bookmark
  urlContext: bookmarks
  interactions:
    - description: It shall respond 404 if the bookmark cannot be found by ID
      request:
        get: ${randomInt()}
      response:
        status: 404
```

Here `${randomInt()}` returns back a random integer. However if we migrate this app to MongoDB/Morphia, `${randomInt()} wont be able to work as usually a mongodb entity use `ObjectId` as entity id.

This CR is to propose an new function that allows developer specify a random valid id generated for a certain type, e.g. `${randomId(User)` will generate a valid id for `User` model.
