### ISSUE TITLE
Act-Test - Add `In` verifier

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#1271]
This verifier allows it to check if a given value is inside a predefined list, e.g.

```yaml
Scenario(1262):
  description: "Support JSON path #1262"
  interactions:
  - description: test 1
    request:
      get: 1262?_jsonPath=$.roles.name
    response:
      json:
        size:
          - gt: 0
        ?:
          - in: guest,account_manager,user,user-manager,order-manager
```
