### ISSUE TITLE
Support different test engines

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#1339]
At the moment act-test allows to run API test. This CR is to allow it run different test engines, e.g. selenium webdriver test engine that run UI tests. 

Proposed selenium test scripts:

```yaml
Scenario(UI-Login):
  description: Login test user
  steps:
    - navigate: "/login"
    - send-keys:
        target: "#input-username"
        keys: "testuser"
    - send-keys:
        target: "#input-password"
        keys: "secret"
    - click: "#btn-login"
    - wait-till-visible: "body.dashboard"
```

Note this CR is only about providing the mechanism supporting multiple test engines. The selenium test engine implementation is not in the scope. Instead refer to https://github.com/actframework/act-selenium
