### ISSUE TITLE
act-test: number verification logic error

### ISSUE THREAD

**Issue by CrossLee** [actframework/actframework#1361]
test scenario yaml:
```
Scenario(create order):
  description: create order test
  fixtures:
    - profit-config-data.yml
  interactions:
    - description: create order test
      request:
        headers:
          Accept: text/html
        get: /test/profit/order
        params:
          stationId: 1
          copId: 1
          staffId: 1
          giftId: 56
          number: 1
          zhifuMethod: WEIXIN_FUWUSHANG_H5SCAN
          totalPrice: 149957
          openId: o7hp206PcK9JFHhsoX76aPPCS5x4
      response:
        json:
          shOrderDetailList:
            0:
              staffAProfitPrice: 27478
```

response json:
```
{
    "remark": "",
    "shOrder": {
        "actualtotalprice": 149957,
        "copId": 1,
        "createTime": 1597915313613,
        "id": 97,
        "mobile": "",
        "openid": "",
        "out_trade_no": "1597915313617WXSPJS97",
        "staffId": 1,
        "stationId": 1,
        "status": "Daizhifu",
        "totalprice": 149957,
        "type": "0",
        "updateTime": 1597915313613,
        "userId": 1,
        "zhifumethod": "WEIXIN_FUWUSHANG_H5SCAN"
    },
    "shOrderDetailList": [
        {
            "actualTotalPrice": 249987,
            "copId": 1,
            "createTime": 1597915313619,
            "giftId": 56,
            "num": 1,
            "orderId": 97,
            "price": 249987,
            "staffAProfit": 1100,
            "staffAProfitPrice": 27498,
            "staffAProfitType": "1",
            "staffId": 1,
            "stationId": 1,
            "stationProfit": 100000,
            "stationProfitPrice": 100000,
            "stationProfitType": "2",
            "status": "Daizhifu",
            "totalPrice": 300000,
            "type": 0,
            "updateTime": 1597915313619
        }
    ],
    "succ": true
}
```

it should verify failed with staffAProfitPrice(27498 === 27478), but test case result is PASS
![image](https://user-images.githubusercontent.com/4584905/90857995-db8a0f80-e3b7-11ea-82a0-79d68161731f.png)

expect:
number verification should be perfect matching, above case should be FAIL
