### ISSUE TITLE
Act-Test - support sending request with file array

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#1375]
At the moment it doesn't support building a test request with multipart field with array element. This CR is the enhance the parsing logic and allow building multipart form request with arrays, e.g.

```yaml
Scenario(1352):
  description: "Wrong file object inject from form field into the controller param"
  interactions:
  - description: Test
    request:
      post: 1352
      parts:
        selectValues:
          - abc
          - xyz
        file: test.txt
        files:
          - test.txt
          - test.txt
    response:
      json:
        result: true
```
