### ISSUE TITLE
Add new inferface to get permit from acl.yaml

### ISSUE THREAD

**Issue by leeaee** [actframework/actframework#143]
```
root:
  type: privilege
  level: 9999

admin-read:
  type: permission
  dynamic: false

admin-change:
  type: permission
  dynamic: false

```
Could act supply an interface to get one/all permits from acl.yaml.

1. Get one permission object by the permit(etc. admin-read).
```json
{
  "permit": "admin-read",
  "type": "permission",
  "dynamic": false
}
```
2. Get all permission as one list.
```json 
["admin-read", "admin-change"]
```
3. Get one permission related i18n value by the permit. (etc. admin-read)
i18n properties file may like
```
permit.admin-read: Read administrator permission.
permit.admin-change: Update/modify administrator permission.
```
```json
{
  "admin-read": "Read administrator permission."
}
```
4. Get all permission related i18n values as one list.
```json
[
  {"admin-read": "Read administrator permission."},
  {"admin-change": "Update/modify administrator permission."}
]
```
