### ISSUE TITLE
Support passing settings via environment variable

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#636]
This feature is specifically design to make it easy to configure act application via docker-compose file. For example:

```
version: '3'
services:
    mongo:
        image: mongo
        container_name: mongo
        ports:
            - 27017
        hostname: mongo
    app:
        image: "thinkingstudio/cicd_todo_backend:1.0-SNAPSHOT-b180418_1118"
        container_name: act_app
        links:
            - mongo:mongo
        hostname: act
        environment:
            - act_env_db_host=mongo
        ports:
            - "5460"
```

In the above code `act_evn_db_host` shall be converted to `db.host` configuration.

One of the thing is this won't work for the configuration item contains `_` , for example `api_doc.enabled` and `built_in_req_handler` etc. This issue will be address by #635
