### ISSUE TITLE
e2e - support embed function in string for constant definition

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#788]
Sample scenario.yml file:

```yaml
Scenario(Sign up user):
  constants:
    newUserFirstName: ${randFirstName()}
    newUserLastName: ${randLastName()}
    newUserEmail: htdi001+e2e-${randStr()}@outlook.com
```

In the `newUserEmail` constant definition we embedded the `${randStr()}` function in a normal string
