### ISSUE TITLE
e2e - support email content verification

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#789]
Proposed interaction:

```yaml
    - description: verify sign up email
      preActions:
        - pause: 1000 * 20
      request:
        email: ${newUserEmail}
      response:
        html:
          p:
            <any>:
              - contains: please click the following link to activate your account
          a#activate-link:
            - notEmpty: true
```
