### ISSUE TITLE
e2e function: It generated invalid email

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#799]
Scenario yaml file source:

```yaml
Scenario(SignUp):
  constants:
    newUserFirstName: ${randFirstName()}
    newUserLastName: ${randLastName()}
    newUserEmail: ${verifiableEmail()}
    newUserPassword: ${randStr()}
```

Error encountered:

```
javax.mail.internet.AddressException: Domain contains illegal character in string ``htdi001+u5@@outlook.com''
```

Problem is the `verifiableEmail()` function generated invalid email address: `htdi001+u5@@outlook.com`, note the double `@` in the email.
