### ISSUE TITLE
e2e - random model data generation

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#800]
At the moment it supports load fixtures from yaml file. However it is not a small effort when it needs to generate bulk data.

This requirement is to provide a mechanism to automatically generate testing data for e2e tests

**Comment by greenlaw110** [comment]
Support new component in Scenario definition:

```yaml
Scenario(Prepare):
  generateTestData:
    - htdi.act.usrmgr.models.User
```

The above specification asks e2e generate 100 User records

Or 

```yaml
Scenario(Prepare):
  generateTestData:
    htdi.act.usrmgr.models.User: 10
```

The above specification asks e2e generate 10 User records
