### ISSUE TITLE
e2e: Allow suppress fixture clearing

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#805]
In case it needs to e2e on existing database, it shall allow developer to suppress fixture clearing. Proposed scenario definition:

```yaml
Scenario(FOO):
    clearFixtures: false
    interactions:
...
```
