### ISSUE TITLE
Test - Allow app to define url context for scenario

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#869]
Proposed Scenario yaml file:

```yaml
Scenario(Create Workspace):
  urlContext: /api/v2
  interactions:
      - description: create workspace with dir that does not exists
        request:
          post: workspaces
          params:
            dir: dir_not_exists
        response:
          status: 400
```

With `urlContext` defined as `/api/v2` in the scanrio, the post URL `workspaces` will become `/api/v2/workspaces`. 

**Note** if the request URL starts with `/` then it indicate an absolute URL and shall not be concatenated to `urlContext` even if it exists.
