### ISSUE TITLE
Test: evaluation complex expression refer to cached object issue

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#871]
Suppose there is a cached object named `rawFileSchema`:

```json
{
  "id": 1
}
```

Trying to evaluate the following expression won't work:

```yaml
      response:
        json:
          name: dir1
          masterSchema:
            id: ${rawFileSchema.id} # this line breaks
```
