### ISSUE TITLE
Test Scenario - allow using `me` to refer to the whole response

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#899]
E.g.

```yaml
Scenario(Fibonacci):
  constants:
    expected: ${fs(16)}
  interactions:
    - description: load fibonacciSeries
      request:
        get: /fs?max=16
      response:
        json:
          me:
            - eq: ${expected}
            - fs: 16
```

In the above scenario definition (coming from https://github.com/act-gallery/test-demo/blob/master/src/main/resources/test/scenarios/timestamp.yml), we use `me` to refer to the entire JSON array returned in the response body.
