### ISSUE TITLE
Test - allow setting precision of ${now()} function

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#908]
It found the following scenario failed after a set of improvement has been done in test verifiers and functions (specifically date time related):

```yaml
Scenario(Did you know):
  partition: admin
  depends:
    - Admin Login
  constants:
    startTs: ${now()}
    title1: ${randomStr()}
    brokerMsg1: ${randomStr()}
    title2: ${randomStr()}
    brokerMsg2: ${randomStr()}
  urlContext: /admin/dyk_msgs
  interactions:
    - description: create DYK message
      request:
        post: ""
        json:
          title: ${title1}
          brokerMsg: ${brokerMsg1}
      response:
        json:
          id:
            - exists: true
      cache:
        id1: id
    - description: verify DYK message creation
      request:
        get: ${id1}
      response:
        json:
          id: ${id1}
          title: ${title1}
          brokerMsg: ${brokerMsg1}
          created:
            - after: ${startTs}
```

The root cause is identified: the `startTs` which is assigned by calling test function `${now()}` has a precision of milliseconds, while the returned timestamp `created` has a precision of seconds. thus the verifier `after: ${startTs}` failed.

Before the precision setting is implemented, it shall change the default precision to second instead of millisecond
