### ISSUE TITLE
Test - allow it add `negative` decorator to verifier

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#910]
E.g.

```yaml
Scenario(GH908):
  description: "[908] Test - allow setting precision of ${now()} function"
  constants:
    startTs: ${now()}
  interactions:
  - description: Test
    request:
      get: 908
    response:
      json:
        result:
          - "!before": ${startTs}
```

Where `"!before"` is used to express a `NOT` `before` semantic.

Since YAML does not allow using `!before` directly and it must be enclosed with `"`, `"`, we provide the following way as an alternative notation:

* `-before`
* `not:before`
